# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployTemplateCharacter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'template_character.zip'
        path: ./template_character
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: actions/checkout@master
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "template_character.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
    
      
    

        
